name: action-shell-test
description: 'test shell'
branding:
  icon: package
  color: yellow

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      id: default-python
      with:
        python-version: "3.x"
    - name: setup environment
      shell: bash
      id: setup
      run: |
        set -euxo pipefail
        python -m venv 'venv A'
        mkdir 'test A'
        echo "print(__file__)" >> 'test A/test.py'
        TEST_PATH="$(pwd)/test A/test.py"
        if [ -d './venv A/bin' ]; then
            PYTHON_PATH="$(pwd)/venv A/bin/python"
        else
            PYTHON_PATH="$(pwd)/venv A/Scripts/python.exe"
            PYTHON_PATH="$(cygpath -w "${PYTHON_PATH}")"
            TEST_PATH="$(cygpath -w "${TEST_PATH}")"
        fi
        echo "python=${PYTHON_PATH}" >> "$GITHUB_OUTPUT"
        echo "test=${TEST_PATH}" >> "$GITHUB_OUTPUT"

    - name: works with shell
      shell: bash
      run: "'${{ steps.setup.outputs.python }}' '${{ steps.setup.outputs.test }}'"

    - name: python shell workaround
      shell: bash
      run: |
        "${{ steps.setup.outputs.python }}" -u << "EOF"
        print(__file__)
        EOF

    - name: python shell
      shell: ${{ steps.default-python.outputs.python-path }} -u {0}
      run: print(__file__)

# Error: Could not find a part of the path '/opt/hostedtoolcache/Python/3.12.2/x64/bin/'/home/runner/work/sandbox/sandbox'.
# Error: Could not find a part of the path '/Users/runner/hostedtoolcache/Python/3.12.2/x64/bin/'/Users/runner/work/sandbox/sandbox'.
# Error: The filename, directory name, or volume label syntax is incorrect. : 'C:\hostedtoolcache\windows\Python\3.12.2\x64\Scripts\'D:\a\sandbox\sandbox'
#    - name: python shell
#      shell: "'${{ steps.setup.outputs.python }}' -u '{0}'"
#      run: print(__file__)

#    - name: python shell
#      shell: ${{ steps.setup.outputs.python }} -u {0}
#      run: print(__file__)
