name: Sandbox

on:
  push:
  workflow_dispatch:
    # allow manual runs on branches without a PR

jobs:
  sandbox:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "graalpy-24.0.2"
    - name: test
      run: |
        python -m pip install -U pip
        python -m pip install -U certifi
