name: SandBox

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions: {}

jobs:
  setup_python:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    container:
      image: quay.io/pypa/manylinux_2_28:latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "ubuntu-24.04-arm"]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Prepare container
        run: ./prepare-container.sh
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          allow-prereleases: true
          python-version: |
            3.9
            3.10
            3.11
            3.12
            3.13
            3.14
            3.14t
            3.15
            3.15t
      - name: Run tests
        run: python -VV
