name: Timings

on:
  push:
    branches:
      - manylinux-interpreters
  workflow_dispatch:
    # allow manual runs on branches without a PR

jobs:
  timings:
    name: Timings
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_x86_64:latest
    steps:
    - uses: actions/checkout@v3
    - name: Remove existing PyPy
      run: |
        rm -rf /usr/local/bin/pypy*
        rm -rf /opt/python/pp*
        rm -rf /opt/_internal/pypy*
    -run: python3.10 -u ./build_scripts/manylinux-python.py ensure pp37-pypy37_pp73
    -run: python3.10 -u ./build_scripts/manylinux-python.py ensure pp38-pypy38_pp73
    -run: python3.10 -u ./build_scripts/manylinux-python.py ensure pp39-pypy39_pp73
    -run: python3.10 -u ./build_scripts/manylinux-python.py ensure pp310-pypy310_pp73
    -run: python3.10 -u ./build_scripts/manylinux-python.py ensure graalpy310-graalpy230_310_native
